-- GENERATED by scripts/gen-team-stats-mvs.ts on 2026-09-16 — do not hand-edit.
--
-- Widened team × game_year materialized views for /api/scene-stats teamStats
-- (Graphics → Team Stats) and /api/team-tendencies. Existing columns are the
-- deployed definitions verbatim; appended columns use lib/reportMetrics.METRICS.
--
-- Apply (build takes minutes — run it in the background, not over HTTP):
--   1. Create/replace the function below (fast).
--   2. SELECT cron.schedule('rebuild_team_stats_mvs_once', '* * * * *', 'SELECT rebuild_team_stats_mvs()');
--      The function takes an advisory lock (overlapping ticks exit immediately)
--      and unschedules the job when the swap has committed.
--   3. Watch: SELECT status, return_message, start_time, end_time
--            FROM cron.job_run_details ORDER BY start_time DESC LIMIT 5;
-- Nightly: refresh_materialized_views() REFRESHes both views CONCURRENTLY by
-- name, so it keeps working after the swap. NB rebuild_savant_mvs() still
-- carries the OLD narrow definitions — re-run this after it if it is ever used.
--
-- Pitching columns (55): team, game_year, pitches, games, pa, avg_velo, whiff_pct, k_pct, bb_pct, avg_xwoba, csw_pct, zone_pct, chase_pct, strikeouts, walks, hbp_count, home_runs, ip, xwoba_raw, woba_raw, max_velo, avg_spin, avg_hbreak_in, avg_ivb_in, avg_ext, avg_arm_angle, k_minus_bb, swstr_pct, contact_pct, z_swing_pct, o_contact_pct, ba, obp, slg, ops, avg_xba, avg_xslg, avg_woba, total_re24, avg_ev, max_ev, avg_la, avg_dist, hard_hit_pct, barrel_pct, gb_pct, fb_pct, ld_pct, iffb_pct, h, hr_count, k_count, bb_count, doubles, triples
-- Batting columns  (53): team, game_year, pitches, games, pa, runs, avg_ev, ba, slg, k_pct, bb_pct, avg_xwoba, hard_hit_pct, barrel_pct, woba_raw, whiff_pct, k_minus_bb, csw_pct, swstr_pct, zone_pct, chase_pct, contact_pct, z_swing_pct, o_contact_pct, obp, ops, avg_xba, avg_xslg, avg_woba, total_re24, max_ev, avg_la, avg_dist, gb_pct, fb_pct, ld_pct, iffb_pct, avg_bat_speed, avg_swing_length, avg_attack_angle, avg_attack_direction, avg_swing_path_tilt, fast_swing_rate, squared_up_rate, blast_rate, ideal_attack_angle_rate, h, hr_count, k_count, bb_count, doubles, triples, hbp_count

CREATE OR REPLACE FUNCTION public.rebuild_team_stats_mvs()
RETURNS text
LANGUAGE plpgsql
SET statement_timeout TO '3600s'
AS $fn$
DECLARE
  t0 timestamptz := clock_timestamp();
BEGIN
  IF NOT pg_try_advisory_xact_lock(hashtext('rebuild_team_stats_mvs')) THEN
    RETURN 'busy: another rebuild is running';
  END IF;

  -- mv_team_pitching_stats: build alongside the live view (no lock on the live one)
  EXECUTE 'DROP MATERIALIZED VIEW IF EXISTS mv_team_pitching_stats_new';
  EXECUTE $mv$CREATE MATERIALIZED VIEW mv_team_pitching_stats_new AS
 SELECT
        CASE
            WHEN inning_topbot = 'Top'::text THEN home_team
            ELSE away_team
        END AS team,
    game_year,
    count(*)::integer AS pitches,
    count(DISTINCT game_pk)::integer AS games,
    count(DISTINCT
        CASE
            WHEN events IS NOT NULL AND (events <> ALL (ARRAY['truncated_pa'::text, 'game_advisory'::text, 'ejection'::text, 'wild_pitch'::text, 'passed_ball'::text, 'other_advance'::text, 'runner_double_play'::text, 'caught_stealing_2b'::text, 'caught_stealing_3b'::text, 'caught_stealing_home'::text, 'pickoff_1b'::text, 'pickoff_2b'::text, 'pickoff_3b'::text, 'pickoff_caught_stealing_2b'::text, 'pickoff_caught_stealing_3b'::text, 'pickoff_caught_stealing_home'::text, 'stolen_base_2b'::text, 'stolen_base_3b'::text, 'stolen_base_home'::text])) THEN game_pk::bigint * 10000 + at_bat_number
            ELSE NULL::bigint
        END)::integer AS pa,
    round(avg(release_speed)::numeric, 1) AS avg_velo,
    round(100.0 * count(*) FILTER (WHERE description ~~ '%swinging_strike%'::text OR (description = ANY (ARRAY['missed_bunt'::text, 'swinging_pitchout'::text, 'foul_tip'::text, 'bunt_foul_tip'::text])))::numeric / NULLIF(count(*) FILTER (WHERE description ~~ '%swinging_strike%'::text OR description ~~ '%foul%'::text OR description ~~ 'hit_into_play%'::text OR description = 'missed_bunt'::text OR description = 'swinging_pitchout'::text), 0)::numeric, 1) AS whiff_pct,
    round(100.0 * count(*) FILTER (WHERE events ~~ '%strikeout%'::text)::numeric / NULLIF(count(DISTINCT
        CASE
            WHEN events IS NOT NULL AND (events <> ALL (ARRAY['truncated_pa'::text, 'game_advisory'::text, 'ejection'::text, 'wild_pitch'::text, 'passed_ball'::text, 'other_advance'::text, 'runner_double_play'::text, 'caught_stealing_2b'::text, 'caught_stealing_3b'::text, 'caught_stealing_home'::text, 'pickoff_1b'::text, 'pickoff_2b'::text, 'pickoff_3b'::text, 'pickoff_caught_stealing_2b'::text, 'pickoff_caught_stealing_3b'::text, 'pickoff_caught_stealing_home'::text, 'stolen_base_2b'::text, 'stolen_base_3b'::text, 'stolen_base_home'::text])) THEN game_pk::bigint * 10000 + at_bat_number
            ELSE NULL::bigint
        END), 0)::numeric, 1) AS k_pct,
    round(100.0 * count(*) FILTER (WHERE events = ANY (ARRAY['walk'::text, 'intent_walk'::text]))::numeric / NULLIF(count(DISTINCT
        CASE
            WHEN events IS NOT NULL AND (events <> ALL (ARRAY['truncated_pa'::text, 'game_advisory'::text, 'ejection'::text, 'wild_pitch'::text, 'passed_ball'::text, 'other_advance'::text, 'runner_double_play'::text, 'caught_stealing_2b'::text, 'caught_stealing_3b'::text, 'caught_stealing_home'::text, 'pickoff_1b'::text, 'pickoff_2b'::text, 'pickoff_3b'::text, 'pickoff_caught_stealing_2b'::text, 'pickoff_caught_stealing_3b'::text, 'pickoff_caught_stealing_home'::text, 'stolen_base_2b'::text, 'stolen_base_3b'::text, 'stolen_base_home'::text])) THEN game_pk::bigint * 10000 + at_bat_number
            ELSE NULL::bigint
        END), 0)::numeric, 1) AS bb_pct,
    round(((COALESCE(sum(estimated_woba_using_speedangle) FILTER (WHERE description ~~ 'hit_into_play%'::text), 0::real) + (0.7 * count(*) FILTER (WHERE events = 'walk'::text)::numeric)::double precision + (0.7 * count(*) FILTER (WHERE events = 'hit_by_pitch'::text)::numeric)::double precision) / NULLIF(count(*) FILTER (WHERE events = ANY (ARRAY['single'::text, 'double'::text, 'triple'::text, 'home_run'::text, 'field_out'::text, 'strikeout'::text, 'strikeout_double_play'::text, 'grounded_into_double_play'::text, 'force_out'::text, 'double_play'::text, 'field_error'::text, 'fielders_choice'::text, 'fielders_choice_out'::text, 'triple_play'::text, 'other_out'::text, 'walk'::text, 'hit_by_pitch'::text, 'sac_fly'::text, 'sac_fly_double_play'::text])), 0)::double precision)::numeric, 3) AS avg_xwoba,
    round(100.0 * count(*) FILTER (WHERE description ~~ '%swinging_strike%'::text OR description = 'called_strike'::text OR description = 'missed_bunt'::text OR description = 'swinging_pitchout'::text)::numeric / NULLIF(count(*), 0)::numeric, 1) AS csw_pct,
    round(100.0 * count(*) FILTER (WHERE zone >= 1::double precision AND zone <= 9::double precision)::numeric / NULLIF(count(*) FILTER (WHERE zone IS NOT NULL), 0)::numeric, 1) AS zone_pct,
    round(100.0 * count(*) FILTER (WHERE zone > 9::double precision AND (description ~~ '%swinging_strike%'::text OR description ~~ '%foul%'::text OR description ~~ 'hit_into_play%'::text OR description = 'missed_bunt'::text OR description = 'swinging_pitchout'::text))::numeric / NULLIF(count(*) FILTER (WHERE zone > 9::double precision), 0)::numeric, 1) AS chase_pct,
    count(*) FILTER (WHERE events ~~ '%strikeout%'::text)::integer AS strikeouts,
    count(*) FILTER (WHERE events = ANY (ARRAY['walk'::text, 'intent_walk'::text]))::integer AS walks,
    count(*) FILTER (WHERE events = 'hit_by_pitch'::text)::integer AS hbp_count,
    count(*) FILTER (WHERE events = 'home_run'::text)::integer AS home_runs,
    round((count(DISTINCT
        CASE
            WHEN events IS NOT NULL AND (events <> ALL (ARRAY['single'::text, 'double'::text, 'triple'::text, 'home_run'::text, 'walk'::text, 'intent_walk'::text, 'hit_by_pitch'::text, 'catcher_interf'::text, 'field_error'::text, 'truncated_pa'::text, 'game_advisory'::text, 'ejection'::text, 'wild_pitch'::text, 'passed_ball'::text, 'other_advance'::text, 'runner_double_play'::text, 'caught_stealing_2b'::text, 'caught_stealing_3b'::text, 'caught_stealing_home'::text, 'pickoff_1b'::text, 'pickoff_2b'::text, 'pickoff_3b'::text, 'pickoff_caught_stealing_2b'::text, 'pickoff_caught_stealing_3b'::text, 'pickoff_caught_stealing_home'::text, 'stolen_base_2b'::text, 'stolen_base_3b'::text, 'stolen_base_home'::text])) THEN game_pk::bigint * 10000 + at_bat_number
            ELSE NULL::bigint
        END) + count(DISTINCT
        CASE
            WHEN events ~~ '%double_play%'::text THEN game_pk::bigint * 10000 + at_bat_number
            ELSE NULL::bigint
        END) + 2 * count(DISTINCT
        CASE
            WHEN events = 'triple_play'::text THEN game_pk::bigint * 10000 + at_bat_number
            ELSE NULL::bigint
        END))::numeric / 3.0, 1) AS ip,
    (COALESCE(sum(estimated_woba_using_speedangle) FILTER (WHERE description ~~ 'hit_into_play%'::text), 0::real) + (0.7 * count(*) FILTER (WHERE events = 'walk'::text)::numeric)::double precision + (0.7 * count(*) FILTER (WHERE events = 'hit_by_pitch'::text)::numeric)::double precision) / NULLIF(count(*) FILTER (WHERE events = ANY (ARRAY['single'::text, 'double'::text, 'triple'::text, 'home_run'::text, 'field_out'::text, 'strikeout'::text, 'strikeout_double_play'::text, 'grounded_into_double_play'::text, 'force_out'::text, 'double_play'::text, 'field_error'::text, 'fielders_choice'::text, 'fielders_choice_out'::text, 'triple_play'::text, 'other_out'::text, 'walk'::text, 'hit_by_pitch'::text, 'sac_fly'::text, 'sac_fly_double_play'::text])), 0)::double precision AS xwoba_raw,
    (0.7 * count(*) FILTER (WHERE events = 'walk'::text)::numeric + 0.7 * count(*) FILTER (WHERE events = 'hit_by_pitch'::text)::numeric + 0.9 * count(*) FILTER (WHERE events = 'single'::text)::numeric + 1.25 * count(*) FILTER (WHERE events = 'double'::text)::numeric + 1.6 * count(*) FILTER (WHERE events = 'triple'::text)::numeric + 2.0 * count(*) FILTER (WHERE events = 'home_run'::text)::numeric) / NULLIF(count(*) FILTER (WHERE events = ANY (ARRAY['single'::text, 'double'::text, 'triple'::text, 'home_run'::text, 'field_out'::text, 'strikeout'::text, 'strikeout_double_play'::text, 'grounded_into_double_play'::text, 'force_out'::text, 'double_play'::text, 'field_error'::text, 'fielders_choice'::text, 'fielders_choice_out'::text, 'triple_play'::text, 'other_out'::text, 'walk'::text, 'hit_by_pitch'::text, 'sac_fly'::text, 'sac_fly_double_play'::text])), 0)::numeric AS woba_raw,
    ROUND(MAX(release_speed)::numeric, 1) AS max_velo,
    ROUND(AVG(release_spin_rate)::numeric, 0) AS avg_spin,
    ROUND(AVG(pfx_x * 12)::numeric, 1) AS avg_hbreak_in,
    ROUND(AVG(pfx_z * 12)::numeric, 1) AS avg_ivb_in,
    ROUND(AVG(release_extension)::numeric, 2) AS avg_ext,
    ROUND(AVG(arm_angle)::numeric, 1) AS avg_arm_angle,
    ROUND(100.0 * (COUNT(*) FILTER (WHERE events LIKE '%strikeout%') - COUNT(*) FILTER (WHERE events IN ('walk','intent_walk'))) / NULLIF(COUNT(DISTINCT CASE WHEN events IS NOT NULL AND events NOT IN ('truncated_pa','game_advisory','ejection','wild_pitch','passed_ball','other_advance','runner_double_play','caught_stealing_2b','caught_stealing_3b','caught_stealing_home','pickoff_1b','pickoff_2b','pickoff_3b','pickoff_caught_stealing_2b','pickoff_caught_stealing_3b','pickoff_caught_stealing_home','stolen_base_2b','stolen_base_3b','stolen_base_home') THEN game_pk::bigint * 10000 + at_bat_number END), 0), 1) AS k_minus_bb,
    ROUND(100.0 * COUNT(*) FILTER (WHERE description LIKE '%swinging_strike%' OR description = 'swinging_pitchout') / NULLIF(COUNT(*), 0), 1) AS swstr_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE description IN ('foul','foul_tip','hit_into_play','hit_into_play_no_out','hit_into_play_score','foul_bunt','bunt_foul_tip','foul_pitchout')) / NULLIF(COUNT(*) FILTER (WHERE description LIKE '%swinging_strike%' OR description IN ('foul','foul_tip','hit_into_play','hit_into_play_no_out','hit_into_play_score','foul_bunt','bunt_foul_tip','foul_pitchout','missed_bunt') OR description = 'swinging_pitchout'), 0), 1) AS contact_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE zone BETWEEN 1 AND 9 AND (description LIKE '%swinging_strike%' OR description LIKE '%foul%' OR description LIKE 'hit_into_play%' OR description = 'missed_bunt' OR description = 'swinging_pitchout')) / NULLIF(COUNT(*) FILTER (WHERE zone BETWEEN 1 AND 9), 0), 1) AS z_swing_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE zone > 9 AND description IN ('foul','foul_tip','hit_into_play','hit_into_play_no_out','hit_into_play_score','foul_bunt','bunt_foul_tip','foul_pitchout')) / NULLIF(COUNT(*) FILTER (WHERE zone > 9 AND (description LIKE '%swinging_strike%' OR description IN ('foul','foul_tip','hit_into_play','hit_into_play_no_out','hit_into_play_score','foul_bunt','bunt_foul_tip','foul_pitchout','missed_bunt') OR description = 'swinging_pitchout')), 0), 1) AS o_contact_pct,
    ROUND(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run'))::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out')), 0), 3) AS ba,
    ROUND(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','walk','intent_walk','hit_by_pitch'))::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out','walk','intent_walk','hit_by_pitch','sac_fly','sac_fly_double_play')), 0), 3) AS obp,
    ROUND((COUNT(*) FILTER (WHERE events = 'single') + 2 * COUNT(*) FILTER (WHERE events = 'double') + 3 * COUNT(*) FILTER (WHERE events = 'triple') + 4 * COUNT(*) FILTER (WHERE events = 'home_run'))::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out')), 0), 3) AS slg,
    ROUND(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','walk','intent_walk','hit_by_pitch'))::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out','walk','intent_walk','hit_by_pitch','sac_fly','sac_fly_double_play')), 0) + (COUNT(*) FILTER (WHERE events = 'single') + 2 * COUNT(*) FILTER (WHERE events = 'double') + 3 * COUNT(*) FILTER (WHERE events = 'triple') + 4 * COUNT(*) FILTER (WHERE events = 'home_run'))::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out')), 0), 3) AS ops,
    ROUND(SUM(estimated_ba_using_speedangle)::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out')), 0), 3) AS avg_xba,
    ROUND(SUM(estimated_slg_using_speedangle)::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out')), 0), 3) AS avg_xslg,
    ROUND((0.7 * COUNT(*) FILTER (WHERE events = 'walk') + 0.7 * COUNT(*) FILTER (WHERE events = 'hit_by_pitch') + 0.9 * COUNT(*) FILTER (WHERE events = 'single') + 1.25 * COUNT(*) FILTER (WHERE events = 'double') + 1.6 * COUNT(*) FILTER (WHERE events = 'triple') + 2.0 * COUNT(*) FILTER (WHERE events = 'home_run'))::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out','walk','hit_by_pitch','sac_fly','sac_fly_double_play')), 0), 3) AS avg_woba,
    ROUND(SUM(delta_run_exp)::numeric, 1) AS total_re24,
    ROUND(AVG(launch_speed) FILTER (WHERE bb_type IS NOT NULL)::numeric, 1) AS avg_ev,
    ROUND(MAX(launch_speed) FILTER (WHERE bb_type IS NOT NULL)::numeric, 1) AS max_ev,
    ROUND(AVG(launch_angle) FILTER (WHERE bb_type IS NOT NULL)::numeric, 1) AS avg_la,
    ROUND(AVG(hit_distance_sc) FILTER (WHERE bb_type IS NOT NULL)::numeric, 0) AS avg_dist,
    ROUND(100.0 * COUNT(*) FILTER (WHERE launch_speed >= 95 AND bb_type IS NOT NULL) / NULLIF(COUNT(*) FILTER (WHERE bb_type IS NOT NULL), 0), 1) AS hard_hit_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE launch_speed_angle::text = '6') / NULLIF(COUNT(*) FILTER (WHERE bb_type IS NOT NULL), 0), 1) AS barrel_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE bb_type = 'ground_ball') / NULLIF(COUNT(*) FILTER (WHERE bb_type IS NOT NULL), 0), 1) AS gb_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE bb_type IN ('fly_ball','popup')) / NULLIF(COUNT(*) FILTER (WHERE bb_type IS NOT NULL), 0), 1) AS fb_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE bb_type = 'line_drive') / NULLIF(COUNT(*) FILTER (WHERE bb_type IS NOT NULL), 0), 1) AS ld_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE bb_type = 'popup') / NULLIF(COUNT(*) FILTER (WHERE bb_type IN ('fly_ball','popup')), 0), 1) AS iffb_pct,
    COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run')) AS h,
    COUNT(*) FILTER (WHERE events = 'home_run') AS hr_count,
    COUNT(*) FILTER (WHERE events LIKE '%strikeout%') AS k_count,
    COUNT(*) FILTER (WHERE events IN ('walk','intent_walk')) AS bb_count,
    COUNT(*) FILTER (WHERE events = 'double') AS doubles,
    COUNT(*) FILTER (WHERE events = 'triple') AS triples
   FROM pitches p
  WHERE (COALESCE(pitch_type, ''::text) <> ALL (ARRAY['PO'::text, 'IN'::text])) AND game_type = 'R'::text
  GROUP BY (
        CASE
            WHEN inning_topbot = 'Top'::text THEN home_team
            ELSE away_team
        END), game_year$mv$;
  EXECUTE 'CREATE UNIQUE INDEX mv_team_pitching_stats_new_team_game_year_idx ON mv_team_pitching_stats_new (team, game_year)';
  EXECUTE 'GRANT ALL ON mv_team_pitching_stats_new TO anon, authenticated, service_role';
  RAISE NOTICE 'mv_team_pitching_stats_new built at %', clock_timestamp() - t0;

  -- mv_team_batting_stats: build alongside the live view (no lock on the live one)
  EXECUTE 'DROP MATERIALIZED VIEW IF EXISTS mv_team_batting_stats_new';
  EXECUTE $mv$CREATE MATERIALIZED VIEW mv_team_batting_stats_new AS
 SELECT
        CASE
            WHEN inning_topbot = 'Top'::text THEN away_team
            ELSE home_team
        END AS team,
    game_year,
    count(*)::integer AS pitches,
    count(DISTINCT game_pk)::integer AS games,
    count(DISTINCT
        CASE
            WHEN events IS NOT NULL AND (events <> ALL (ARRAY['truncated_pa'::text, 'game_advisory'::text, 'ejection'::text, 'wild_pitch'::text, 'passed_ball'::text, 'other_advance'::text, 'runner_double_play'::text, 'caught_stealing_2b'::text, 'caught_stealing_3b'::text, 'caught_stealing_home'::text, 'pickoff_1b'::text, 'pickoff_2b'::text, 'pickoff_3b'::text, 'pickoff_caught_stealing_2b'::text, 'pickoff_caught_stealing_3b'::text, 'pickoff_caught_stealing_home'::text, 'stolen_base_2b'::text, 'stolen_base_3b'::text, 'stolen_base_home'::text])) THEN game_pk::bigint * 10000 + at_bat_number
            ELSE NULL::bigint
        END)::integer AS pa,
    sum(COALESCE(post_bat_score, 0) - COALESCE(bat_score, 0)) FILTER (WHERE events IS NOT NULL) AS runs,
    round(avg(launch_speed) FILTER (WHERE bb_type IS NOT NULL)::numeric, 1) AS avg_ev,
    round(count(*) FILTER (WHERE events = ANY (ARRAY['single'::text, 'double'::text, 'triple'::text, 'home_run'::text]))::numeric / NULLIF(count(*) FILTER (WHERE events = ANY (ARRAY['single'::text, 'double'::text, 'triple'::text, 'home_run'::text, 'field_out'::text, 'strikeout'::text, 'strikeout_double_play'::text, 'grounded_into_double_play'::text, 'force_out'::text, 'double_play'::text, 'field_error'::text, 'fielders_choice'::text, 'fielders_choice_out'::text, 'triple_play'::text, 'other_out'::text])), 0)::numeric, 3) AS ba,
    round((count(*) FILTER (WHERE events = 'single'::text) + 2 * count(*) FILTER (WHERE events = 'double'::text) + 3 * count(*) FILTER (WHERE events = 'triple'::text) + 4 * count(*) FILTER (WHERE events = 'home_run'::text))::numeric / NULLIF(count(*) FILTER (WHERE events = ANY (ARRAY['single'::text, 'double'::text, 'triple'::text, 'home_run'::text, 'field_out'::text, 'strikeout'::text, 'strikeout_double_play'::text, 'grounded_into_double_play'::text, 'force_out'::text, 'double_play'::text, 'field_error'::text, 'fielders_choice'::text, 'fielders_choice_out'::text, 'triple_play'::text, 'other_out'::text])), 0)::numeric, 3) AS slg,
    round(100.0 * count(*) FILTER (WHERE events ~~ '%strikeout%'::text)::numeric / NULLIF(count(DISTINCT
        CASE
            WHEN events IS NOT NULL AND (events <> ALL (ARRAY['truncated_pa'::text, 'game_advisory'::text, 'ejection'::text, 'wild_pitch'::text, 'passed_ball'::text, 'other_advance'::text, 'runner_double_play'::text, 'caught_stealing_2b'::text, 'caught_stealing_3b'::text, 'caught_stealing_home'::text, 'pickoff_1b'::text, 'pickoff_2b'::text, 'pickoff_3b'::text, 'pickoff_caught_stealing_2b'::text, 'pickoff_caught_stealing_3b'::text, 'pickoff_caught_stealing_home'::text, 'stolen_base_2b'::text, 'stolen_base_3b'::text, 'stolen_base_home'::text])) THEN game_pk::bigint * 10000 + at_bat_number
            ELSE NULL::bigint
        END), 0)::numeric, 1) AS k_pct,
    round(100.0 * count(*) FILTER (WHERE events = ANY (ARRAY['walk'::text, 'intent_walk'::text]))::numeric / NULLIF(count(DISTINCT
        CASE
            WHEN events IS NOT NULL AND (events <> ALL (ARRAY['truncated_pa'::text, 'game_advisory'::text, 'ejection'::text, 'wild_pitch'::text, 'passed_ball'::text, 'other_advance'::text, 'runner_double_play'::text, 'caught_stealing_2b'::text, 'caught_stealing_3b'::text, 'caught_stealing_home'::text, 'pickoff_1b'::text, 'pickoff_2b'::text, 'pickoff_3b'::text, 'pickoff_caught_stealing_2b'::text, 'pickoff_caught_stealing_3b'::text, 'pickoff_caught_stealing_home'::text, 'stolen_base_2b'::text, 'stolen_base_3b'::text, 'stolen_base_home'::text])) THEN game_pk::bigint * 10000 + at_bat_number
            ELSE NULL::bigint
        END), 0)::numeric, 1) AS bb_pct,
    round(((COALESCE(sum(estimated_woba_using_speedangle) FILTER (WHERE description ~~ 'hit_into_play%'::text), 0::real) + (0.7 * count(*) FILTER (WHERE events = 'walk'::text)::numeric)::double precision + (0.7 * count(*) FILTER (WHERE events = 'hit_by_pitch'::text)::numeric)::double precision) / NULLIF(count(*) FILTER (WHERE events = ANY (ARRAY['single'::text, 'double'::text, 'triple'::text, 'home_run'::text, 'field_out'::text, 'strikeout'::text, 'strikeout_double_play'::text, 'grounded_into_double_play'::text, 'force_out'::text, 'double_play'::text, 'field_error'::text, 'fielders_choice'::text, 'fielders_choice_out'::text, 'triple_play'::text, 'other_out'::text, 'walk'::text, 'hit_by_pitch'::text, 'sac_fly'::text, 'sac_fly_double_play'::text])), 0)::double precision)::numeric, 3) AS avg_xwoba,
    round(100.0 * count(*) FILTER (WHERE launch_speed >= 95::double precision AND bb_type IS NOT NULL)::numeric / NULLIF(count(*) FILTER (WHERE bb_type IS NOT NULL), 0)::numeric, 1) AS hard_hit_pct,
    round(100.0 * count(*) FILTER (WHERE launch_speed_angle::text = '6'::text)::numeric / NULLIF(count(*) FILTER (WHERE bb_type IS NOT NULL), 0)::numeric, 1) AS barrel_pct,
    (0.7 * count(*) FILTER (WHERE events = 'walk'::text)::numeric + 0.7 * count(*) FILTER (WHERE events = 'hit_by_pitch'::text)::numeric + 0.9 * count(*) FILTER (WHERE events = 'single'::text)::numeric + 1.25 * count(*) FILTER (WHERE events = 'double'::text)::numeric + 1.6 * count(*) FILTER (WHERE events = 'triple'::text)::numeric + 2.0 * count(*) FILTER (WHERE events = 'home_run'::text)::numeric) / NULLIF(count(*) FILTER (WHERE events = ANY (ARRAY['single'::text, 'double'::text, 'triple'::text, 'home_run'::text, 'field_out'::text, 'strikeout'::text, 'strikeout_double_play'::text, 'grounded_into_double_play'::text, 'force_out'::text, 'double_play'::text, 'field_error'::text, 'fielders_choice'::text, 'fielders_choice_out'::text, 'triple_play'::text, 'other_out'::text, 'walk'::text, 'hit_by_pitch'::text, 'sac_fly'::text, 'sac_fly_double_play'::text])), 0)::numeric AS woba_raw,
    ROUND(100.0 * COUNT(*) FILTER (WHERE description LIKE '%swinging_strike%' OR description IN ('missed_bunt','swinging_pitchout','foul_tip','bunt_foul_tip')) / NULLIF(COUNT(*) FILTER (WHERE description LIKE '%swinging_strike%' OR description LIKE '%foul%' OR description LIKE 'hit_into_play%' OR description = 'missed_bunt' OR description = 'swinging_pitchout'), 0), 1) AS whiff_pct,
    ROUND(100.0 * (COUNT(*) FILTER (WHERE events LIKE '%strikeout%') - COUNT(*) FILTER (WHERE events IN ('walk','intent_walk'))) / NULLIF(COUNT(DISTINCT CASE WHEN events IS NOT NULL AND events NOT IN ('truncated_pa','game_advisory','ejection','wild_pitch','passed_ball','other_advance','runner_double_play','caught_stealing_2b','caught_stealing_3b','caught_stealing_home','pickoff_1b','pickoff_2b','pickoff_3b','pickoff_caught_stealing_2b','pickoff_caught_stealing_3b','pickoff_caught_stealing_home','stolen_base_2b','stolen_base_3b','stolen_base_home') THEN game_pk::bigint * 10000 + at_bat_number END), 0), 1) AS k_minus_bb,
    ROUND(100.0 * COUNT(*) FILTER (WHERE description LIKE '%swinging_strike%' OR description = 'called_strike' OR description = 'swinging_pitchout') / NULLIF(COUNT(*), 0), 1) AS csw_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE description LIKE '%swinging_strike%' OR description = 'swinging_pitchout') / NULLIF(COUNT(*), 0), 1) AS swstr_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE zone BETWEEN 1 AND 9) / NULLIF(COUNT(*) FILTER (WHERE zone IS NOT NULL), 0), 1) AS zone_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE zone > 9 AND (description LIKE '%swinging_strike%' OR description LIKE '%foul%' OR description LIKE 'hit_into_play%' OR description = 'missed_bunt' OR description = 'swinging_pitchout')) / NULLIF(COUNT(*) FILTER (WHERE zone > 9), 0), 1) AS chase_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE description IN ('foul','foul_tip','hit_into_play','hit_into_play_no_out','hit_into_play_score','foul_bunt','bunt_foul_tip','foul_pitchout')) / NULLIF(COUNT(*) FILTER (WHERE description LIKE '%swinging_strike%' OR description IN ('foul','foul_tip','hit_into_play','hit_into_play_no_out','hit_into_play_score','foul_bunt','bunt_foul_tip','foul_pitchout','missed_bunt') OR description = 'swinging_pitchout'), 0), 1) AS contact_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE zone BETWEEN 1 AND 9 AND (description LIKE '%swinging_strike%' OR description LIKE '%foul%' OR description LIKE 'hit_into_play%' OR description = 'missed_bunt' OR description = 'swinging_pitchout')) / NULLIF(COUNT(*) FILTER (WHERE zone BETWEEN 1 AND 9), 0), 1) AS z_swing_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE zone > 9 AND description IN ('foul','foul_tip','hit_into_play','hit_into_play_no_out','hit_into_play_score','foul_bunt','bunt_foul_tip','foul_pitchout')) / NULLIF(COUNT(*) FILTER (WHERE zone > 9 AND (description LIKE '%swinging_strike%' OR description IN ('foul','foul_tip','hit_into_play','hit_into_play_no_out','hit_into_play_score','foul_bunt','bunt_foul_tip','foul_pitchout','missed_bunt') OR description = 'swinging_pitchout')), 0), 1) AS o_contact_pct,
    ROUND(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','walk','intent_walk','hit_by_pitch'))::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out','walk','intent_walk','hit_by_pitch','sac_fly','sac_fly_double_play')), 0), 3) AS obp,
    ROUND(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','walk','intent_walk','hit_by_pitch'))::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out','walk','intent_walk','hit_by_pitch','sac_fly','sac_fly_double_play')), 0) + (COUNT(*) FILTER (WHERE events = 'single') + 2 * COUNT(*) FILTER (WHERE events = 'double') + 3 * COUNT(*) FILTER (WHERE events = 'triple') + 4 * COUNT(*) FILTER (WHERE events = 'home_run'))::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out')), 0), 3) AS ops,
    ROUND(SUM(estimated_ba_using_speedangle)::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out')), 0), 3) AS avg_xba,
    ROUND(SUM(estimated_slg_using_speedangle)::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out')), 0), 3) AS avg_xslg,
    ROUND((0.7 * COUNT(*) FILTER (WHERE events = 'walk') + 0.7 * COUNT(*) FILTER (WHERE events = 'hit_by_pitch') + 0.9 * COUNT(*) FILTER (WHERE events = 'single') + 1.25 * COUNT(*) FILTER (WHERE events = 'double') + 1.6 * COUNT(*) FILTER (WHERE events = 'triple') + 2.0 * COUNT(*) FILTER (WHERE events = 'home_run'))::numeric / NULLIF(COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run','field_out','strikeout','strikeout_double_play','grounded_into_double_play','force_out','double_play','field_error','fielders_choice','fielders_choice_out','triple_play','other_out','walk','hit_by_pitch','sac_fly','sac_fly_double_play')), 0), 3) AS avg_woba,
    ROUND(SUM(delta_run_exp)::numeric, 1) AS total_re24,
    ROUND(MAX(launch_speed) FILTER (WHERE bb_type IS NOT NULL)::numeric, 1) AS max_ev,
    ROUND(AVG(launch_angle) FILTER (WHERE bb_type IS NOT NULL)::numeric, 1) AS avg_la,
    ROUND(AVG(hit_distance_sc) FILTER (WHERE bb_type IS NOT NULL)::numeric, 0) AS avg_dist,
    ROUND(100.0 * COUNT(*) FILTER (WHERE bb_type = 'ground_ball') / NULLIF(COUNT(*) FILTER (WHERE bb_type IS NOT NULL), 0), 1) AS gb_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE bb_type IN ('fly_ball','popup')) / NULLIF(COUNT(*) FILTER (WHERE bb_type IS NOT NULL), 0), 1) AS fb_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE bb_type = 'line_drive') / NULLIF(COUNT(*) FILTER (WHERE bb_type IS NOT NULL), 0), 1) AS ld_pct,
    ROUND(100.0 * COUNT(*) FILTER (WHERE bb_type = 'popup') / NULLIF(COUNT(*) FILTER (WHERE bb_type IN ('fly_ball','popup')), 0), 1) AS iffb_pct,
    ROUND(AVG(bat_speed)::numeric, 1) AS avg_bat_speed,
    ROUND(AVG(swing_length)::numeric, 2) AS avg_swing_length,
    ROUND(AVG(attack_angle)::numeric, 1) AS avg_attack_angle,
    ROUND(AVG(attack_direction)::numeric, 1) AS avg_attack_direction,
    ROUND(AVG(swing_path_tilt)::numeric, 1) AS avg_swing_path_tilt,
    ROUND(100.0 * COUNT(*) FILTER (WHERE bat_speed >= 75) / NULLIF(COUNT(*) FILTER (WHERE bat_speed IS NOT NULL), 0), 1) AS fast_swing_rate,
    ROUND(100.0 * COUNT(*) FILTER (WHERE launch_speed >= 0.8 * (1.23 * bat_speed + 0.23 * release_speed) AND bat_speed IS NOT NULL AND bb_type IS NOT NULL) / NULLIF(COUNT(*) FILTER (WHERE bat_speed IS NOT NULL AND bb_type IS NOT NULL), 0), 1) AS squared_up_rate,
    ROUND(100.0 * COUNT(*) FILTER (WHERE launch_speed >= 0.8 * (1.23 * bat_speed + 0.23 * release_speed) AND bat_speed >= 75 AND bat_speed IS NOT NULL AND bb_type IS NOT NULL) / NULLIF(COUNT(*) FILTER (WHERE bat_speed IS NOT NULL AND bb_type IS NOT NULL), 0), 1) AS blast_rate,
    ROUND(100.0 * COUNT(*) FILTER (WHERE attack_angle BETWEEN 5 AND 20) / NULLIF(COUNT(*) FILTER (WHERE attack_angle IS NOT NULL), 0), 1) AS ideal_attack_angle_rate,
    COUNT(*) FILTER (WHERE events IN ('single','double','triple','home_run')) AS h,
    COUNT(*) FILTER (WHERE events = 'home_run') AS hr_count,
    COUNT(*) FILTER (WHERE events LIKE '%strikeout%') AS k_count,
    COUNT(*) FILTER (WHERE events IN ('walk','intent_walk')) AS bb_count,
    COUNT(*) FILTER (WHERE events = 'double') AS doubles,
    COUNT(*) FILTER (WHERE events = 'triple') AS triples,
    COUNT(*) FILTER (WHERE events = 'hit_by_pitch') AS hbp_count
   FROM pitches p
  WHERE (COALESCE(pitch_type, ''::text) <> ALL (ARRAY['PO'::text, 'IN'::text])) AND game_type = 'R'::text
  GROUP BY (
        CASE
            WHEN inning_topbot = 'Top'::text THEN away_team
            ELSE home_team
        END), game_year$mv$;
  EXECUTE 'CREATE UNIQUE INDEX mv_team_batting_stats_new_team_game_year_idx ON mv_team_batting_stats_new (team, game_year)';
  EXECUTE 'GRANT ALL ON mv_team_batting_stats_new TO anon, authenticated, service_role';
  RAISE NOTICE 'mv_team_batting_stats_new built at %', clock_timestamp() - t0;

  -- Swap both (fast)
  EXECUTE 'DROP MATERIALIZED VIEW IF EXISTS mv_team_pitching_stats';
  EXECUTE 'ALTER MATERIALIZED VIEW mv_team_pitching_stats_new RENAME TO mv_team_pitching_stats';
  EXECUTE 'ALTER INDEX mv_team_pitching_stats_new_team_game_year_idx RENAME TO mv_team_pitching_stats_team_game_year_idx';

  EXECUTE 'DROP MATERIALIZED VIEW IF EXISTS mv_team_batting_stats';
  EXECUTE 'ALTER MATERIALIZED VIEW mv_team_batting_stats_new RENAME TO mv_team_batting_stats';
  EXECUTE 'ALTER INDEX mv_team_batting_stats_new_team_game_year_idx RENAME TO mv_team_batting_stats_team_game_year_idx';

  -- One-shot scheduling: remove the cron job that triggered us, if any
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'rebuild_team_stats_mvs_once') THEN
    PERFORM cron.unschedule('rebuild_team_stats_mvs_once');
  END IF;
  RETURN 'ok: rebuilt both team MVs in ' || (clock_timestamp() - t0)::text;
END;
$fn$;
