/**
 * Generates scripts/create-team-stats-mvs.sql — the DDL for the widened
 * mv_team_pitching_stats / mv_team_batting_stats (team × game_year).
 *
 * Why generated: the existing columns are taken verbatim from the DEPLOYED
 * view definitions (pg_get_viewdef) so nothing that FIP/xERA/wRC+ or
 * team-tendencies read today changes, and the new columns come straight from
 * lib/reportMetrics.METRICS so the /api/scene-stats MV fast path returns the
 * same numbers as its pitches-table slow path.
 *
 * Usage: npx tsx scripts/gen-team-stats-mvs.ts
 *   → writes scripts/create-team-stats-mvs.sql
 *   → prints the metric keys each MV now carries (paste into scene-stats route)
 *
 * Apply with rebuild_team_stats_mvs() — see the generated file's header.
 */
import { createClient } from '@supabase/supabase-js'
import { readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'
import { METRICS, SCENE_METRICS, ERA_METRIC_KEYS, COMPUTED_METRIC_KEYS } from '../lib/reportMetrics'

for (const line of readFileSync(resolve(process.cwd(), '.env.local'), 'utf8').split('\n')) {
  const m = line.match(/^([A-Z_]+)=(.*)$/)
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^"|"$/g, '')
}
const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!)
const q = async (sql: string) => {
  const { data, error } = await sb.rpc('run_query', { query_text: sql })
  if (error) throw new Error(error.message)
  return data as any[]
}

const PITCHING_EXCLUDED_GROUPS = new Set(['Swing', 'Triton', 'Triton+', 'Deception', 'ERA Estimators', 'Info'])
const BATTING_EXCLUDED_GROUPS = new Set(['Stuff', 'Triton', 'Triton+', 'Deception', 'ERA Estimators', 'Info'])
const NEVER = new Set(['usage_pct', 'player_name'])

function newColumns(existing: string[], excludedGroups: Set<string>, extraSkip: string[] = []) {
  const skip = new Set([...existing, ...extraSkip, ...NEVER])
  const keys: string[] = []
  for (const m of SCENE_METRICS) {
    if (!m.group || excludedGroups.has(m.group)) continue
    if (ERA_METRIC_KEYS.has(m.value) || COMPUTED_METRIC_KEYS.has(m.value)) continue
    if (!METRICS[m.value] || skip.has(m.value)) continue
    keys.push(m.value)
  }
  return keys
}

async function build(mv: string, excludedGroups: Set<string>, extraSkip: string[]) {
  const [{ def }] = await q(`SELECT pg_get_viewdef('${mv}'::regclass, true) AS def`)
  const cols = (await q(
    `SELECT a.attname FROM pg_attribute a WHERE a.attrelid='${mv}'::regclass AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum`
  )).map(r => r.attname as string)
  const marker = '\n   FROM pitches p\n'
  const idx = def.indexOf(marker)
  if (idx < 0 || def.indexOf(marker, idx + 1) >= 0) throw new Error(`${mv}: expected exactly one FROM marker`)
  const added = newColumns(cols, excludedGroups, extraSkip)
  const addedSql = added.map(k => `    ${METRICS[k]} AS ${k}`).join(',\n')
  const body = def.slice(0, idx).replace(/\s+$/, '') + ',\n' + addedSql + def.slice(idx).replace(/;\s*$/, '')
  // Validate: planner accepts it (columns exist, syntax OK); LIMIT 0 returns
  // before the scan starts (run_query allows SELECT only, so no EXPLAIN)
  await q(`SELECT * FROM (${body}) v LIMIT 0`)
  return { body, cols, added, all: [...cols, ...added] }
}

async function main() {
  const pitching = await build('mv_team_pitching_stats', PITCHING_EXCLUDED_GROUPS, [])
  const batting = await build('mv_team_batting_stats', BATTING_EXCLUDED_GROUPS, ['ip'])

  const buildSection = (mv: string, body: string) => `
  -- ${mv}: build alongside the live view (no lock on the live one)
  EXECUTE 'DROP MATERIALIZED VIEW IF EXISTS ${mv}_new';
  EXECUTE $mv$CREATE MATERIALIZED VIEW ${mv}_new AS
${body}$mv$;
  EXECUTE 'CREATE UNIQUE INDEX ${mv}_new_team_game_year_idx ON ${mv}_new (team, game_year)';
  EXECUTE 'GRANT ALL ON ${mv}_new TO anon, authenticated, service_role';
  RAISE NOTICE '${mv}_new built at %', clock_timestamp() - t0;
`
  // Swaps run last so the AccessExclusiveLock from DROP is held only until
  // COMMIT a few ms later, not for the duration of the other view's build.
  const swapSection = (mv: string) => `
  EXECUTE 'DROP MATERIALIZED VIEW IF EXISTS ${mv}';
  EXECUTE 'ALTER MATERIALIZED VIEW ${mv}_new RENAME TO ${mv}';
  EXECUTE 'ALTER INDEX ${mv}_new_team_game_year_idx RENAME TO ${mv}_team_game_year_idx';
`

  const sql = `-- GENERATED by scripts/gen-team-stats-mvs.ts on ${new Date().toISOString().slice(0, 10)} — do not hand-edit.
--
-- Widened team × game_year materialized views for /api/scene-stats teamStats
-- (Graphics → Team Stats) and /api/team-tendencies. Existing columns are the
-- deployed definitions verbatim; appended columns use lib/reportMetrics.METRICS.
--
-- Apply (build takes minutes — run it in the background, not over HTTP):
--   1. Create/replace the function below (fast).
--   2. SELECT cron.schedule('rebuild_team_stats_mvs_once', '* * * * *', 'SELECT rebuild_team_stats_mvs()');
--      The function takes an advisory lock (overlapping ticks exit immediately)
--      and unschedules the job when the swap has committed.
--   3. Watch: SELECT status, return_message, start_time, end_time
--            FROM cron.job_run_details ORDER BY start_time DESC LIMIT 5;
-- Nightly: refresh_materialized_views() REFRESHes both views CONCURRENTLY by
-- name, so it keeps working after the swap. NB rebuild_savant_mvs() still
-- carries the OLD narrow definitions — re-run this after it if it is ever used.
--
-- Pitching columns (${pitching.all.length}): ${pitching.all.join(', ')}
-- Batting columns  (${batting.all.length}): ${batting.all.join(', ')}

CREATE OR REPLACE FUNCTION public.rebuild_team_stats_mvs()
RETURNS text
LANGUAGE plpgsql
SET statement_timeout TO '3600s'
AS $fn$
DECLARE
  t0 timestamptz := clock_timestamp();
BEGIN
  IF NOT pg_try_advisory_xact_lock(hashtext('rebuild_team_stats_mvs')) THEN
    RETURN 'busy: another rebuild is running';
  END IF;
${buildSection('mv_team_pitching_stats', pitching.body)}${buildSection('mv_team_batting_stats', batting.body)}
  -- Swap both (fast)${swapSection('mv_team_pitching_stats')}${swapSection('mv_team_batting_stats')}
  -- One-shot scheduling: remove the cron job that triggered us, if any
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'rebuild_team_stats_mvs_once') THEN
    PERFORM cron.unschedule('rebuild_team_stats_mvs_once');
  END IF;
  RETURN 'ok: rebuilt both team MVs in ' || (clock_timestamp() - t0)::text;
END;
$fn$;
`
  writeFileSync(resolve(process.cwd(), 'scripts/create-team-stats-mvs.sql'), sql)
  console.log('wrote scripts/create-team-stats-mvs.sql')
  console.log('PITCHING existing:', pitching.cols.join(', '))
  console.log('PITCHING added   :', pitching.added.join(', '))
  console.log('BATTING existing :', batting.cols.join(', '))
  console.log('BATTING added    :', batting.added.join(', '))
  console.log('ROUTE_PITCHING_KEYS', JSON.stringify(pitching.all))
  console.log('ROUTE_BATTING_KEYS', JSON.stringify(batting.all))
}
main().catch(e => { console.error(e); process.exit(1) })
